#!/usr/bin/env python3
"""Generate consolidated security reports."""
import json
import sys
from collections import Counter
from pathlib import Path

def load_findings(scan_dir):
    p = Path(scan_dir)
    for name in ["deduplicated-findings.json", "normalized-findings.json"]:
        f = p / name
        if f.exists():
            return json.loads(f.read_text())
    return []

def load_metadata(scan_dir):
    f = Path(scan_dir) / "scan-metadata.json"
    if f.exists():
        return json.loads(f.read_text())
    return {}

def generate_report(findings, metadata, full=False):
    lines = []
    repo = metadata.get("repo", "Unknown")
    date = metadata.get("date", "Unknown")
    branch = metadata.get("branch", "main")
    commit = metadata.get("commit", "unknown")[:8]

    sev_counts = Counter(f["severity"] for f in findings)
    tool_counts = Counter()
    for f in findings:
        for t in f.get("detected_by", [f.get("source", "unknown")]):
            tool_counts[t] += 1

    lines.append(f"# Security Report: {repo}")
    lines.append(f"")
    lines.append(f"**Date:** {date}  ")
    lines.append(f"**Branch:** {branch}  ")
    lines.append(f"**Commit:** {commit}  ")
    lines.append(f"**Tools:** {len(tool_counts)}  ")
    lines.append(f"")
    lines.append(f"## Executive Summary")
    lines.append(f"")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    for sev in ["critical", "high", "medium", "low", "info"]:
        if sev_counts.get(sev, 0) > 0 or sev in ("critical", "high"):
            lines.append(f"| {sev} | {sev_counts.get(sev, 0)} |")
    lines.append(f"| **Total** | **{len(findings)}** |")
    lines.append(f"")

    for sev in ["critical", "high"]:
        sev_findings = [f for f in findings if f["severity"] == sev]
        if sev_findings:
            lines.append(f"## {sev.title()} Findings ({len(sev_findings)})")
            lines.append(f"")
            lines.append(f"| # | Source | File | Line | Title | Detected By |")
            lines.append(f"|---|--------|------|------|-------|-------------|")
            for i, f in enumerate(sev_findings[:50], 1):
                detected = ", ".join(f.get("detected_by", [f.get("source", "")]))
                title = f["title"][:60]
                lines.append(f"| {i} | {f['source']} | {f['file']} | {f.get('line_start', '-')} | {title} | {detected} |")
            if len(sev_findings) > 50:
                lines.append(f"| ... | | | | +{len(sev_findings) - 50} more | |")
            lines.append(f"")

    if full:
        for sev in ["medium", "low", "info"]:
            sev_findings = [f for f in findings if f["severity"] == sev]
            if sev_findings:
                lines.append(f"## {sev.title()} Findings ({len(sev_findings)})")
                lines.append(f"")
                lines.append(f"| # | Source | File | Line | Title |")
                lines.append(f"|---|--------|------|------|-------|")
                for i, f in enumerate(sev_findings[:30], 1):
                    lines.append(f"| {i} | {f['source']} | {f['file']} | {f.get('line_start', '-')} | {f['title'][:60]} |")
                if len(sev_findings) > 30:
                    lines.append(f"| ... | | | | +{len(sev_findings) - 30} more |")
                lines.append(f"")

    lines.append(f"## Tool Coverage")
    lines.append(f"")
    lines.append(f"| Tool | Findings | Category |")
    lines.append(f"|------|----------|----------|")
    for tool, count in tool_counts.most_common():
        cat_counts = Counter(f["category"] for f in findings if tool in f.get("detected_by", [f.get("source", "")]))
        top_cat = cat_counts.most_common(1)[0][0] if cat_counts else "-"
        lines.append(f"| {tool} | {count} | {top_cat} |")
    lines.append(f"")

    lines.append(f"## Recommendations")
    lines.append(f"")
    recs = [f for f in findings if f.get("recommendation") and f["severity"] in ("critical", "high")]
    seen = set()
    n = 0
    for f in recs:
        rec = f["recommendation"][:200]
        if rec not in seen:
            n += 1
            seen.add(rec)
            lines.append(f"{n}. **{f['title'][:60]}**: {rec}")
            if n >= 5:
                break
    if n == 0:
        lines.append("No specific recommendations from tool output.")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"*Generated by RHOAI Security Audit*")

    return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("scan_dir")
    parser.add_argument("--full", action="store_true")
    args = parser.parse_args()

    findings = load_findings(args.scan_dir)
    metadata = load_metadata(args.scan_dir)
    print(generate_report(findings, metadata, full=args.full))


if __name__ == "__main__":
    main()
